name: ModernLeaderboards
version: '${project.version}'
main: dev.enco.modernleaderboards.Main
api-version: '1.18'
depend: [ajLeaderboards, PlaceholderAPI, FancyHolograms]
commands:
  greataligner:
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin.version}